import * as firebase from 'firebase';
import Rebase from 're-base';

// const config = {
//   apiKey: process.env.REACT_APP_FIREBASE_KEY,
//   authDomain: process.env.REACT_APP_FIREBASE_DOMAIN,
//   databaseURL: process.env.REACT_APP_FIREBASE_DATABASE,
//   projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID,
//   storageBucket: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
//   messagingSenderId: process.env.REACT_APP_FIREBASE_SENDER_ID,
// };

const config = {
  apiKey: 'AIzaSyCIHqdl2GqIMEoXn-0oLR5Hm00_eZE1zts',
  authDomain: 'intelli-guide.firebaseapp.com',
  databaseURL: 'https://intelli-guide.firebaseio.com',
  projectId: 'intelli-guide',
  storageBucket: 'intelli-guide.appspot.com',
  messagingSenderId: '846727200470',
};

firebase.initializeApp(config);
export const database = firebase.database();
export const fetchPermanent = () => {
  database.ref('permanent').on('value', snapshot => {
    console.log(snapshot.key, snapshot.val());
  });
};

// fetchPermanent();

// database
//   .ref()
//   .set({
//     copyright:
//       'Worldwide rights ©Salvador Dalí. Fundació Gala-Salvador Dalí (Artists Rights Society), 2017 / In the USA ©Salvador Dalí Museum, Inc. St. Petersburg, FL 2017.',
//     permanent: [
//       {
//         title: 'View of Cadaqués with Shadow of Mount Pani',
//         url: 'http://archive.thedali.org/MWEBimages/Collection Images/1980.7_thumbnail.jpg',
//         maker: 'Salvador Dalí',
//         dateMade: 1917,
//         placeMade: 'Spain',
//         materials: 'Oil on burlap',
//         dimensions: '15 1/2 in x 19 in',
//         accessionIDNumber: 1980.7,
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         exhibitionHistory: [
//           '1925, Barcelona, Galeries Dalmau, "Exposició S. Dalí"',
//           '1995, St. Petersburg, Salvador Dali Museum, "The Young Dali: Works from 1914-1930"',
//           '2004, Venezia, Palazzo Grassi, "Dalí"',
//           '2005, Philadelphia, The Philadelphia Museum of Art, "Dalí"',
//           '2016, Tokyo, National Art Center, "Salvador Dalí"',
//           '2016, Kyoto, Kyoto Municipal Museum, "Salvador Dalí"',
//         ],
//         description: [
//           'During this period Dalí was experimenting with Impressionism, a 19th Century art movement that sought to capture the immediacy of the visual moment by painting the effects of light on the surfaces of objects. The work is painted on rough burlap, which gives the Bay of Cadaqués scene, with its blocky houses and shimmering sea, an assertive texture. At the invitation of Dalí’s father’s friend Jose Pepito Pichot, Dalí offered to visit the Pichot family estate just outside of Figueres. The Pichots were an extended family whose many members included proficient musicians and artists. Dalí’s father believed an association with this artistic and musically talented family would be very beneficial to his son. In the Pichot dining room, the walls were lined with impressionist paintings, some by Ramon Pichot, an established Impressionist painter and a close friend of Pablo Picasso (1881-1976). One day while looking at Ramon’s works Dalí decided to become a painter. Dalí later said, “Impressionist painting attracted me at the time because it was considered anti-establishment and a revolutionary aesthetic theory.”',
//         ],
//       },
//       {
//         title: 'Daddy Longlegs of the Evening-Hope!',
//         url: 'http://archive.thedali.org/MWEBimages/Collection Images/2000.6_thumbnail.jpg',
//         maker: 'Salvador Dalí',
//         dateMade: 1940,
//         placeMade: 'Unied States',
//         materials: 'Oil on burlap',
//         dimensions: '10 in x 20 in',
//         accessionIDNumber: 2000.6,
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         history: [
//           '1941, Chicago, The Arts Club of Chicago, “Salvador Dali”',
//           '1941, New York, Julien Levy Gallery, “Salvador Dalí”',
//           '1941, Los Angeles, Dalzell Hatfield Galleries, “Salvador Dalí”',
//           '1943, New York, Art of this Century, “Art of this Century : 15 Early Paintings. 15 Late Paintings”',
//           '1947, Cleveland, Cleveland Museum of Art, “Print Club of Cleveland-Salvador Dalí: An Exhibition”',
//           '1954, Roma, Sale dellAurora Pallavicini, “Mostra di quadri disegni ed oreficerie di Salvador Dalí”',
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '2000, St. Petersburg, Florida, The Salvador Dalí Museum, “James Rosenquist: Paintings James Rosenquist: Selects DALI”',
//           '2004, Venezia, Palazzo Grassi, Dali Retrospective',
//           '2005, Philadelphia, Philadelphia Museum of Art, Dali Retrospective',
//           '2006, Tokyo, Ueno Royal Museum, “Dalí Centennial Retrospective”',
//           '2007, St. Petersburg, Fl., Salvador Dalí Museum, “Dalí and the Spanish Baroque”',
//           '2007, St. Petersburg, Fl., Salvador Dalí Museum, “Dalí and the Spanish Baroque”',
//           '2009, Melbourne, National Gallery of Victoria, Salvador Dalí : Liquid Desire',
//         ],
//         description: [
//           'Daddy Longlegs of the Evening - Hope! (Araignée du soir, espoir) - 1940. (Including: soft aeroplane, vomited by a cannon, ants, victory born of a broken wing, violoncello in white mastic, and an angel who weeps).',
//           'Dalí and his wife, Gala, stayed in the United States from 1940 to 1948 due to the war in Europe which drove him and his fellow Surrealists into exile. This was the first painting Dalí completed after coming to America. The victory referred to in the title is the classical sculpture of the winged Nike of Samothrace who emerges shrouded while rising from the limp airplane. The cannon from the deflated plane is reminiscent of Giorgio de Chirico’s The Philosopher Conquest of 1914. ',
//           'An anguished head occupies the center, but here it has become a soft structure infused with sunset colors. The head is metamorphosed into an elastic female figure whose breasts are mimicked by two inkwells (erotic symbols in Dalí’s iconography) which suggest the signing of treaties (and Dalí’s father’s role as a notary). Ants eat away at the figure’s mouth as they do in countless other paintings, indicating the insidious destruction swallowing Europe. The viscous cello and bow suggest that all of Europe’s highest precepts were helpless to prevent the destruction of culture at the hands of a fascist regime.',
//           'The painting’s title refers to an old French peasant legend: a spider seen in the evening is a symbol of good luck. ',
//         ],
//       },
//       {
//         url: 'http://archive.thedali.org/MWEBimages/Collection Images/1983.1_thumbnail.jpg',
//         title: 'Self-Portrait',
//         maker: 'Salvador Dalí',
//         dateMade: '1921',
//         placeMade: 'Spain',
//         materials: 'Oil on burlap',
//         dimensions: '14 1/2 in x 16 1/2 in',
//         accessionIDNumber: '1983.1',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           'This self-portrait was painted during the most tumultuous time in Dalí’s life. Dalí’s mother, Felipa Doménech i Ferrés (1874-1921) died of cancer on February 8, 1921. Yet shortly after, Dalí was accepted to the San Fernando Royal Academy of Fine Arts in Madrid, which he began attending in the fall of 1922. The young artist has represented himself as a young dandy, wearing a large floppy black hat, a black cape, a bold red scarf, and sporting a pipe, creating an unusual appearance that gained him some notoriety among the other students at the Residencia de Estudiantes in Madrid. That Dalí chose to use these props for this early self-portrait indicates that at the age of seventeen, he was already consciously building an eccentric public personality.',
//           'Dalí’s eccentricity developed even earlier in an attempt to establish his own distinct identity. Dalí’s identity crisis was the result of having a brother who died nine months before his own birth and who was also named Salvador Dalí. The artist felt that his parents wanted him to be the replacement for the dead brother. Yet Dalí’s eccentricities helped him achieve a separate unique identity.',
//           'Notable is the artist’s use of chiaroscuro, a technique where strong dark and light areas are contrasted to produce form.',
//           'Notable is the artist’s use of chiaroscuro, a technique where strong dark and light areas are contrasted to produce form.',
//         ],
//         exhibitionHistory: [
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '1994, Madrid, Museo Nacional Centro de Arte Reina Sofía, "Dalí Joven, 1918-1930"',
//           '1994, New York, Metropolitan Museum of Art, "Dalí: The Early Years"',
//           '1994, London, Hayward Gallery, "Dalí: The Early Years"',
//           '1995, Barcelona, Palau Robert, "Dalí: els Anys Joves, 1918-1930"',
//           '1995, St. Petersburg, Salvador Dali Museum, “The Young Dali: Works from 1914-1930”',
//           '1996, San Antonio, San Antonio Museum of Art, “From Gaudi to Tapies: 20th Century Masters”',
//           '1996, St. Petersburg, The Salvador Dalí Museum, “From Gaudi to Tapies: 20th Century Masters”',
//           '1996, Atlanta, Michael C. Carlos Museum, “From Gaudi to Tapies: 20th Century Masters”',
//           '1997, Tacoma, Tacoma Museum of Art',
//           '1999, Fukuoka, Fukuoka Asian Art Museum, "Dalí Exhibition 1999"',
//           '1999, Shinjuku(Tokyo), Mitsukoshi Museum of Art, "Dalí Exhibition 1999"',
//           '2006, Tokyo, Ueno Royal Museum, “Dalí Centennial Retrospective”',
//           '2007, Osaka, Suntory Museum, "Dalí Multifaceted : Centenary Exhibition"',
//           '2007, Nagoya, Nagoya City Art Museum, "Dalí Multifaceted : Centenary Exhibition"',
//           '2007, Sapporo, Hokkaido Museum of Modern Art, "Dalí Multifaceted : Centenary Exhibition"',
//           '2007, Figueras, Teatro Museu Dalí, Prestec temporal a la Fundacio Gala-Salvador Dalí per a l\'exposicio "Autoretrats"',
//           '2012, Paris, Centre Pompidou, “Dalí Retrospective”',
//           '2013, Madrid, Museo Nacional Reina Sofia, “Dalí. Todas las sugestiones poéticas y todas las posibilidades plásticas”',
//           '2014, St. Petersburg, Salvador Dalí Museum, "Picasso/Dalí Dalí/Picasso"',
//           '2015, Barcelona, Musee Picasso, "Picasso/Dalí Dalí/Picasso"',
//         ],
//       },
//       {
//         url: 'http://archive.thedali.org/MWEBimages/Collection Images/1983.2_thumbnail.jpg',
//         title: 'Cadaqués',
//         maker: 'Salvador Dalí',
//         dateMade: '1923',
//         placeMade: 'Spain',
//         materials: 'Oil on Canvas',
//         dimensions: '38 in x 50 in',
//         accessionIDNumber: '1983.2',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           'Figueres is located inland from the Costa Brava in an area called the Empordà at the foot of the Pyrenees near the French border. The landscape in this region was to be a major influence and inspiration to Dalí throughout his artistic career. The seemingly endless plain that surrounds Figueres, the distant horizon, the white beaches of Rosas, and the rugged cliffs of the Albares Mountains recur in every period of Dalí’s work. ',
//           'In the summers of Dalí’s youth, the family often retreated to their residence in the nearby coastal town. This is an expansive view of Cadaqués from the rock terraces above the Dalí family home. The dynamic composition of this work about his homeland uses a traditional form to establish the subject’s tranquillity. The balloon rising above the landscape and the tiny white sailboat on the expansive bay below create a feeling of lightness and space.',
//           'If these seven young women appear similar to one another, it is because Dalí used his sister, Anna Maria (1908–1990), as the model for all of them. She was Dalí’s only sibling and was his primary model in the years before he met his future wife, Gala, in 1929.',
//         ],
//         exhibitionHistory: [
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '1994, Madrid, Museo Nacional Centro de Arte Reina Sofía, "Dalí Joven, 1918-1930"',
//           '1994, New York, Metropolitan Museum of Art, "Dalí: The Early Years"',
//           '1994, London, Hayward Gallery, "Dalí: The Early Years"',
//           '1995, Barcelona, Palau Robert, "Dalí: els Anys Joves, 1918-1930"',
//           '1995, St. Petersburg, Salvador Dali Museum, “The Young Dali: Works from 1914-1930”',
//           '2000, St. Petersburg, Florida, The Salvador Dalí Museum, “James Rosenquist: Paintings James Rosenquist: Selects DALI”',
//           '2006, Cleveland, Cleveland Museum of Art, “Barcelona & Modernity: Picasso, Gaudi, Miro, Dalí (1868-1939)”',
//           '2007, New York, Metropolitan Museum of Art, “Barcelona & Modernity: Picasso, Gaudi, Miro, Dalí (1868-1939)”',
//           '2009, Melbourne, National Gallery of Victoria, "Salvador Dalí : Liquid Desire"',
//           '2016, Tokyo, National Art Center, “Salvador Dalí” ',
//           '2016, Kyoto, Kyoto Municipal Museum, “Salvador Dalí”',
//         ],
//       },
//       {
//         url:
//           'http://archive.thedali.org/MWEBimages/Collection Images/OILS_images saved for Web/1983.3_Portrait of My Sister_after conservation_web.jpg',
//         title: 'Portrait of My Sister',
//         maker: 'Salvador Dalí',
//         dateMade: '1923',
//         placeMade: 'Spain',
//         materials: 'Oil on Canvas',
//         dimensions: '50 1/4 in x 38 3/4 in x 2 1/2 in',
//         accessionIDNumber: '1983.3',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           'When this work was first exhibited in Spain, it brought the 19-year-old artist considerable fame and was recognized as being comparable to Picasso’s Portrait of Gertrude Stein,1906, or his equally great Women in White, 1923. Dalí completed the first version of Portrait of My Sister in 1923, and originally represented his sister, Anna María, seated in an armchair with her hands crossed in her lap; a small table with books on top occupied the lower right-hand corner. Approximately four years later, Dalí returned to this celebrated canvas and transformed it by adding the second upside-down figure, which radically contrasts with the first and makes the finished painting a double portrait. While there is no documentation that details why Dalí transformed this work so thoroughly, it is believed to be either a reflection of Picasso’s profound influence after their first meeting in 1926, or as a symbol of developing tension between the artist and his sister.',
//         ],
//         exhibitionHistory: [
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '1995, St. Petersburg, Salvador Dali Museum, “The Young Dali: Works from 1914-1930”',
//           '2006, Cleveland, Cleveland Museum of Art, “Barcelona & Modernity: Picasso, Gaudi, Miro, Dalí (1868-1939)”',
//           '2007, New York, Metropolitan Museum of Art, “Barcelona & Modernity: Picasso, Gaudi, Miro, Dalí (1868-1939)”',
//           '2014, St. Petersburg, Salvador Dali Museum, "PicassoDalí Dalí/Picasso"',
//           '2015, Barcelona, Musee Picasso, "PicassoDalí Dalí/Picasso"',
//         ],
//       },
//       {
//         url: 'http://archive.thedali.org/MWEBimages/Collection Images/1981.1_thumbnail.jpg',
//         title: 'The Basket of Bread',
//         maker: 'Salvador Dalí',
//         dateMade: '1926',
//         placeMade: 'Spain',
//         materials: 'Oil on Wood panel',
//         dimensions: '12 1/2 in x 12 1/2 in',
//         accessionIDNumber: '1981.1',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           'This Realist panel demonstrates that by 1926, Dalí’s formative years were drawing to a close; Dalí could achieve mastery in whatever style he chose. This painting has another distinction – it was one of the first Dalí paintings to be seen in America. In 1928 it was exhibited at the Carnegie Institute in Pittsburgh, along with two other works. The artist’s use of detailed illusionism and dramatic lighting against an almost black background alludes to the influence of the Spanish painter Francisco de Zurbarán (1598-1664), demonstrated in his work Still Life with Lemons, Oranges and a Rose, 1633. A contemporary of Diego Velázquez (1599-1660), de Zurbarán was renowned for his works’ austere piety and quiet beauty. Dalí saw bread as the staple of life of the Catalan people. Bread was the most basic element that united Catalans in their daily lives, and like Vermeer and Zurbarán, he renders it as a sublime symbol. ',
//           'The painstaking realism of The Basket of Bread was a major achievement and marked a turning point in his career. It boosted Dalí’s ego and gave him a sense of mastery with traditional painting, freeing him to explore more difficult subject matter and imagery. This simple composition of bread in a straw basket on cloth is set dramatically against a dark background. Dalí followed in the Spanish still-life tradition, where a domestic scene represents spiritual reflection. By saturating the objects in such a mysterious light, he transforms the composition into an object of deep contemplation.',
//         ],
//         exhibitionHistory: [
//           '1926, Barcelona, Galeries Dalmau, "Exposició S. Dalí" ',
//           '1928, Pittsburgh, Carnegie Institute, "Twenty-Seventh International Exhibition of Paintings"',
//           '1932, Pittsburgh, Carnegie Institute, "An Exhibition of Carnegie International Paintings Owned in Pittsburgh"',
//           '1941, New York, The Museum of Modern Art, "Salvador Dalí"',
//           '1942, Indianapolis, The John Herron Art Institute (Indianapolis Museum of Art), [Exhibition of paintings by Salvador Dali] ',
//           '1943, Detroit, Detroit Institute of Arts, "Exhibition of paintings by Salvador Dali"',
//           '1946, Boston, The Institute of Modern Art, "Four Spaniards : Dalí, Gris, Miro, Picasso"',
//           '1965, New York, Gallery of Modern Art, "Salvador Dalí, 1910-1965"',
//           '1993, Figueres, Teatre-Museu Dalí, "Dalí, el Pa"',
//           '1994, Madrid, Museo Nacional Centro de Arte Reina Sofía, "Dalí Joven, 1918-1930"',
//           '1994, New York, Metropolitan Museum of Art, "Dalí: The Early Years"',
//           '1994, London, Hayward Gallery, "Dalí: The Early Years"',
//           '1995, Barcelona, Palau Robert, "Dalí: els Anys Joves, 1918-1930"',
//           '1995, St. Petersburg, Salvador Dali Museum, “The Young Dali: Works from 1914-1930”',
//           '1997, New York, Museum of Modern Art, Objects of Desire: the Modern Still Life"',
//           '1998, Pittsburgh, Andy Warhol Museum of Art, “Dalí at the Warhol”',
//           '1999, Bilbao, Museo de Bellas Artes de Bilbao, "El Bodegón Español: de Zurbarán a Picasso"',
//           '1999, Tokyo, Mitsukoshi Museum of Art, "Dalí Exhibition 1999"',
//           '1999, Fukuoka, Fukuoka Asian Art Museum, "Dalí Exhibition 1999"',
//           '2004, Venezia, Palazzo Grassi, "Dalí Retrospective"',
//           '2005, Philadelphia, Philadelphia Museum of Art, "Dalí Retrospective"',
//           '2006, Tokyo, Ueno Royal Museum, "Salvador Dalí Centennial Retrospective"',
//           '2007, St. Petersburg, Fl., Salvador Dalí Museum, "Dalí and the Spanish Baroque"',
//           '2016, St. Petersburg, Fl., Salvador Dalí Museum, "Ferran Adrià: The Invention of Food"',
//           '2017, London, Royal Academy of the Arts, "Dalí/Duchamp"',
//           '2018, St. Petersburg, The Dalí Museum, "Dalí/Duchamp"',
//         ],
//       },
//       {
//         url:
//           'http://archive.thedali.org/MWEBimages/Collection Images/OILS_images saved for Web/1981.2_Girl-with-Curls_web_before conservation.jpg',
//         title: 'Girl with Curls',
//         maker: 'Salvador Dalí',
//         dateMade: '1926',
//         placeMade: 'Spain',
//         materials: 'Oil on panel',
//         dimensions: '20 in x 15 3/4 in',
//         accessionIDNumber: '1981.2',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           'This work foreshadows Dalí’s Surrealist style, for it presents a mysterious tableaux painted with hallucinatory clarity. While the blend of realism and distortion in Girl with Curls offers a glimpse of the Surrealist style Dalí would become famous for, it was painted three years before he joined the movement. Several ambiguous elements in the composition make it feel more like a dream than a representation of reality. First, judging by the scale of the building next to the girl, she appears to be too large for the landscape in which she stands. Secondly, the girl’s face is hidden from view, creating a sense of mystery and not providing any psychological details that her features could provide. And lastly, while the landscape is painted in a fairly realistic manner, the curves of the girl’s body are highly exaggerated – looking like she stepped out of a dream. This girl originated in childhood fantasies about a fictional Russian girl whom he nicknamed “Galuchka.” He saw this girl in one of the images in an optical theater/stereoscopic box in the house of his childhood teacher, Señor Trayter. These images “were to stir [Dalí] for the rest of his life”. She became his dream girl onto whom he could project all of his desires.',
//           'Dalí pays homage to neoclassicism and its Catalan variant Noucentisme proposed by the writer Eugenio D\'Ors in this alluring painting. Here he represents the unusual the view of a young girl seen from behind and located in an Ampurdán landscape treated in an Italianate style. The representation of a figure viewed from behind is a pretext for painting the expansive landscape imbued with psychological tension, with its high sky and dramatic crescent moon, as we are invited to look over her shoulder and therefore identify with her point of view. Though her sculptural pose ( or "contrapposto") and the treatment of the landscape point to classical motifs, the device of looking over her shoulder derives from Romantic painting, and her exaggeratedly curving hips introduce the erotic into what is otherwise a restrained subject.',
//           "Dalí later explained how this figure was transformed from the adolescent girl Dullita into the literary figure of Gradiva and eventually reborn as his wife Gala. Gradiva was a mythic, literary phantasm, who was notable for how her foot was elegantly raised when walking, the subject of a popular novel analyzed by Freud at the beginning of the 1900s, but only translated into French in 1931. At this time Dalí adopted this subject, making it part of his personal mythology and imbuing this figure with subjective symbolism. Indeed, Gradiva became one of the artist's central concerns during the 1930s.",
//         ],
//         exhibitionHistory: [
//           '1926, Barcelona, Galeries Dalmau, "Exposició S. Dalí"',
//           '1962, Madrid, Casón del Buen Retiro, "Exposición de pintura catalana : desde la prehistoria hasta nuestros días"',
//           '1965, New York, Gallery of Modern Art, "Salvador Dalí, 1910-1965"',
//           '1995, St. Petersburg, Salvador Dali Museum, “The Young Dali: Works from 1914-1930”',
//           '1998, Liverpool, Tate Gallery Liverpool, "Salvador Dalí: a Mythology"',
//           '2000, St. Petersburg, Florida, Salvador Dalí Museum, "James Rosenquist: Paintings"',
//           '2002, Madrid, Museo Thyssen-Bornemisza, "Dalí : Gradiva"',
//           '2016, Tokyo, National Art Center, “Salvador Dalí” ',
//           '2016, Kyoto, Kyoto Municipal Museum, “Salvador Dalí”',
//         ],
//       },
//       {
//         url: 'http://archive.thedali.org/MWEBimages/Collection Images/1995.1_thumbnail.jpg',
//         title: 'Portrait of My Dead Brother',
//         maker: 'Salvador Dalí',
//         dateMade: '1963',
//         placeMade: 'Spain',
//         materials: 'Oil on canvas',
//         dimensions: '69 in x 69 in',
//         accessionIDNumber: '1995.1',
//         creditLine: 'Purchased by the Salvador Dalí Museum, Inc.',
//         onView: true,
//         description: [
//           'This unusual painting refers to one of the key stories in the artist’s life, his relationship with his dead brother. While Salvador was named after his father, Salvador Dalí i Cusi, he also shared this name with his brother, Salvador Galo Anselmo Dalí, who died of infectious stomach inflammation in 1903.',
//           'Dalí felt his parents wanted him to be a replacement for his dead brother, so he cultivated his eccentric behavior to prove that he was different. Dalí often referred to himself and his dead brother as Castor and Pollux, the Roman twins born of Leda. Dalí felt that although his brother was dead, he was still a specter in his life.',
//           'Dalí wrote a brief, elusive description of this work when it was first exhibited. “The Vulture, according to the Egyptians and Freud, represents my mother’s portrait. The cherries represent the molecules, the dark cherries create the visage of my dead brother, the sun-lighted cherries create the image of Salvador living thus repeating the great myth of the Dioscures Castor and Pollux.”',
//           'The source for the brother’s face is currently unknown, although it is believed to be from a newspaper photograph. The style in which Dalí painted his brother resembles an enlarged photograph, with the large dots resembling the Ben Day dots used in photogravure. This also recalls the contemporaneous work of Pop artist Roy Lichtenstein, suggesting new interests in Dalí’s world.',
//         ],
//         exhibitionHistory: [
//           '1963, New York, M. Knoedler @ Co., Inc., “Dalí : Hommage à Crick et Watson”',
//           '1964, Kyoto, Municipal Art Gallery, “Salvador Dalí, 1964”',
//           '1964, Nagoya, Prefectural Museum of Art, “Salvador Dalí, 1964”',
//           '1964, Tokyo, Hotel Prince Gallery, “Salvador Dalí, 1964”',
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '1969, San Diego, Fine Arts Gallery of San Diego, “Legacy of Spain-20th Century”',
//           '1973, Stockholm, Moderna Museet, “Salvador Dalí, 1973”',
//           '1973, Humlebaek, Louisiana Museum of Modern Art, “Rétrospective Salvador Dalí”',
//           '1974, Frankfurt, Stadelsches Kunstinstitut, “Salvador Dalí, 1974”',
//           "1979, Paris, Musee National d'Art Moderne, Centre Georges Pompidou, “Salvador Dalí Retrospective 1920-1980”",
//           '1980, London, Tate Gallery, “Salvador Dalí, 1980”',
//           '1981 & 1982, Tokyo, Osaka, Kitakyusha and Hiroshima, Japan, “Salvador Dalí, 1981-82”',
//           '1989, Humlebaek, Louisiana Museum of Modern Art, "Salvador Dalí"',
//           '1989, Stuttgart, Staatsgalerie Stuttgart, “Salvador Dalí Retrospective”',
//           '1989, Zurich, Kunsthaus, “Salvador Dalí Retrospective”',
//           '1990, Montreal, Montreal Museum of Fine Art, “Salvador Dali”',
//           '1998, Pittsburgh, Andy Warhol Museum of Art, “Dali at the Warhol”',
//           '1998, Liverpool, Tate Gallery, “Dali: A Mythology”',
//           '1998, New York, Solomon R. Gugenheim Museum',
//           "2000, Hartford, Connecticut, Wadsworth Atheneum Museum of Art, “Dalí's Optical Illusions”",
//           "2000, Washington, D.C., Hirshhorn Museum and Sculpture Garden, “Dalí's Optical Illusions”",
//           "2000, Edinburgh, Scottish National Gallery of Modern Art, “Dalí's Optical Illusions”",
//           '2004, Venezia, Palazzo Grassi, "Dali Retrospective"',
//           '2005, Philadelphia, Philadelphia Museum of Art, "Dali Retrospective"',
//           '2005, St. Petersburg, Salvador Dali Museum, "Pollock to Pop: America\'s Brush with Dali"',
//           '2006, Koln, Ludwig Museum, “Le Gare de Perpignan”',
//           '2010, Atlanta, High Museum of Art, “Salvador Dalí: The Late Work”',
//           '2012, Paris, Centre Pompidou, “Dali: Retrospective”',
//           '2013, Madrid, Museo Nacional Reina Sofia, “Dalí. Todas las sugestiones poéticas y todas las posibilidades plásticas”',
//           '2015, St. Petersburg, Salvador Dali Museum, “Dali & da Vinci: Minds, Machines & Masterpieces”',
//         ],
//       },
//       {
//         url:
//           'http://archive.thedali.org/MWEBimages/Collection Images/OILS_images saved for Web/1991.1_Apparatus-and-Hand_web.jpg',
//         title: 'Apparatus and Hand',
//         maker: 'Salvador Dalí',
//         dateMade: '1927',
//         placeMade: 'Spain',
//         materials: '20 1/2 in x 28 1/4 in',
//         dimensions: '20 1/2 in x 28 1/4 in',
//         accessionIDNumber: '1991.1',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           'Dalí painted this work directly after military service when he was 23 years old. In 1923, Sigmund Freud’s Psychopathology of Everyday Life was published in Spanish, followed by the Interpretation of Dreams in 1924. By 1925, Dalí and his friends at the Residencia read them enthusiastically shortly after publication. So it is not surprising that by 1927, Dalí was beginning to employ Freud’s ideas in his work. This pre-Surrealist work foreshadows Dalí’s Surrealist style and is intended to provide the viewer with a spectacle beyond rational comprehension. Symbolic language is employed to record unconscious dream imagery; already Dalí is trying to demonstrate fidelity to his unconscious sources in accordance with Surrealist goals. This is Dalí’s first painting in which elements of Surrealism adorn the landscape. The overall monochromatic tone and illusion of depth further accentuate the dreamlike quality. Apparatus and Hand is reminiscent of the biomorphic shapes that Surrealist Yves Tanguy (1900-1955) created in his work, such as in Genesis, 1926. The triangular shape of the apparatus is repeated in the flight pattern of the birds. In contrast to the strange, otherworldly landscape and elements, the woman’s body is depicted with academic realism. The fish is a reference to the duality of male and female genitalia.',
//         ],
//         exhibitionHistory: [
//           '1927, Barcelona, Sala Parés, Saló de Tardor, núm. cat. 17',
//           '1928, Figueras, Casino Menestral Figuerense, “Catálogo de la Exposición Provincial de Bellas Artes”',
//           '1929, Madrid, Jardín Botánico, “Exposición de Pinturas y Esculturas de Españoles Residentes en París” ',
//           '1929, Paris, Galerie Goemans, “Dalí”',
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '1994, Madrid, Museo Nacional Centro de Arte Reina Sofía, "Dalí Joven, 1918-1930"',
//           '1994, New York, Metropolitan Museum of Art, "Dali: The Early Years"',
//           '1994, London, Hayward Gallery, "Dali: The Early Years"',
//           '1995, Barcelona, Palau Robert, "Dali: els Anys Joves, 1918-1930"',
//           '1995, St. Petersburg, Salvador Dali Museum, “The Young Dali: Works from 1914-1930”',
//           '1999, Fukuoka, Fukuoka Asian Art Museum, "Dali Exhibition 1999"',
//           '1999, Shinjuku(Tokyo), Mitsukoshi Museum of Art, "Dali Exhibition 1999"',
//           "2000, Hartford, Connecticut, Wadsworth Atheneum Museum of Art, “Dalí's Optical Illusions”",
//           "2000, Washington, D.C., Hirshhorn Museum and Sculpture Garden, “Dalí's Optical Illusions”",
//           "2000, Edinburgh, Scottish National Gallery of Modern Art, “Dalí's Optical Illusions”",
//           '2000, Stuttgart, Staatsgalerie Stuttgart, “Yves Tanguy and Surrealism”',
//           '2001, Paris, Galeries Nationales de Grand Palais, “Paris-Barcelona”',
//           '2002, Barcelona, Musee Picasso, “Paris-Barcelona”',
//           '2004, Madrid, Museo Nacional Centro de Arte Reina Sofia, “Dalí. Cultura de masses”',
//           '2004, Barcelona, CaixaForum, “Dalí. Cultura de masses”',
//           '2005, Rotterdam, Museum Boijmans van Beuningen, “Salvador Dalí and Mass Culture”',
//           '2005, St. Petersburg, Salvador Dalí Museum, “Salvador Dalí and Mass Culture”',
//           '2006, Tokyo, Ueno Royal Museum, “Dalí Centennial Retrospective”',
//           '2007, London, The Tate Modern, “Dali and Film”',
//           '2008, Los Angeles, Los Angeles County Museum of Art, “Dali and Film”',
//           '2008, New York, Metropolitan Museum of Art, “Dali and Film”',
//           '2014, St. Petersburg, Salvador Dali Museum, "Picasso/Dali Dali/Picasso"',
//           '2015, Barcelona, Musee Picasso, "Picasso/Dali Dali/Picasso"',
//         ],
//       },
//       {
//         url:
//           'http://archive.thedali.org/MWEBimages/Collection Images/OILS_images saved for Web/2004.1_Gala Contemplating_after conservation_2016_web_web .jpg',
//         title:
//           'Gala Contemplating the Mediterranean Sea which at Twenty Meters Becomes the Portrait of Abraham Lincoln-Homage to Rothko (Second Version)',
//         maker: 'Salvador Dalí',
//         dateMade: '1976',
//         placeMade: '',
//         materials: 'Oil on canvas',
//         dimensions: '99 1/4 in x 75 1/2 in',
//         accessionIDNumber: '2004.1',
//         creditLine: 'Purchased by the Salvador Dalí Museum, Inc.',
//         onView: true,
//         description: [
//           'Gala Contemplating the Mediterranean Sea… demonstrates a fascination with perception and the mystery of identity. Dalí layers multiple optical scales to create two paintings in one. This painting is based on a photograph that Dalí first saw in the November, 1973 issue of Scientific American. Vol. 229. No.5.. The article, “The Recognition of Faces” by Leon D. Harmon, featured a reproduced low resolution (252 pixels) monochromatic photograph of the face of Abraham Lincoln from an American $5 bill. Harmon’s computer generated “coarse –scale” portrait demonstrated the low quantity of information needed to represent a recognizable individual face. The concept awaked Dalί’s old fascination with paranoia – specifically, how much of the reading of an image is from the viewer as distinct from the thing viewed. By squinting slightly and so flattening the depth of field, the portrait of Lincoln snaps into view displacing the figure of Gala. Once seen, the image appears at each return.',
//           'Gala Contemplating the Mediterranean Sea… demonstrates a fascination with perception and the mystery of identity. Dalí layers multiple optical scales to create two paintings in one. This painting is based on a photograph that Dalí first saw in the November, 1973 issue of Scientific American. Vol. 229. No.5.. The article, “The Recognition of Faces” by Leon D. Harmon, featured a reproduced low resolution (252 pixels) monochromatic photograph of the face of Abraham Lincoln from an American $5 bill. Harmon’s computer generated “coarse –scale” portrait demonstrated the low quantity of information needed to represent a recognizable individual face. The concept awaked Dalί’s old fascination with paranoia – specifically, how much of the reading of an image is from the viewer as distinct from the thing viewed. By squinting slightly and so flattening the depth of field, the portrait of Lincoln snaps into view displacing the figure of Gala. Once seen, the image appears at each return.',
//           'Dalí titles the work Homage to Mark Rothko (1903-1970) – a leading abstract expressionist painter who had committed suicide in 1970. Early in his career, Rothko experimented with automatic drawing and surrealist techniques. He studied the writings of Freud as did Dalí. By the 1940s, Rothko abandoned all references to the figurative and painted using simplified shapes, color gradations, and value relationships. Dalí’s multiple blocks of colors in varying progression of hues ending in a dark perimeter is evocative of the meditative “color field” paintings of Rothko. ',
//           'Dalí spent many years living between Spain and the United States and considered America his second home. Dalí painted this work in his room at the St. Régis Hotel in New York. As well as homage to an American painter, the painting is homage to America itself, created in the nation that gave him refuge during the turmoil of Civil and World War Europe. ',
//         ],
//         exhibitionHistory: [
//           '1977, New York, Guggenheim Museum',
//           '1980, London, Tate Gallery, “Salvador Dalí, 1980”',
//           '1981 & 1982, Tokyo, Osaka, Kitakyusha and Hiroshima, Japan, “Salvador Dalí, 1981-82”',
//           '1984, San Antonio, McNay Art Museum',
//           '1985-1987, St. Petersburg, Salvador Dali Museum',
//           '2005, St. Petersburg, Salvador Dali Museum, "Pollock to Pop: America\'s Brush with Dali"',
//         ],
//       },
//       {
//         url: 'http://archive.thedali.org/MWEBimages/Collection Images/1991.2_thumbnail.jpg',
//         title: 'The Average Bureaucrat',
//         maker: 'Salvador Dalí',
//         dateMade: '1030',
//         placeMade: 'Spain',
//         materials: 'Oil on canvas',
//         dimensions: '31 7/8 in x 25 3/4 in',
//         accessionIDNumber: '1991.2',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           "As a Surrealist, Dalí had an aversion to bureaucrats. The surrealists were disgusted by bureaucrats who represented the despised bourgeois. Dalí also shared their aversion to bureaucrats, stemming from his days at the Residencia when he and his friends would depict them as “putrefactes” (“putrescent”), the child-like caricatures Dalí and his friends created to write off people who represented philistine or outmoded ways. Dalí’s father, who had expelled him from the family home, was a notary (responsible for land transactions in their agricultural village), and thus a respected bureaucratic. Dalí’s image of the bureaucrat, which appears often during this period, is both universal and personal, and one of the most enigmatic figures in Dalí's work.",
//           'Dalí’s bureaucrat, whose yellow wax-like skin resembles one of DeChirico’s mannequins, is portrayed as a pathetic figure. Two empty cavities are carved into his head, stressing the emptiness of the skull, and instead of brains Dalí places tiny sea shells and pebbles from the local beaches near his home. In addition, the bureaucrat’s ears have been removed, so he is unable to hear complaints.Yet this harsh attack on his father is tempered by a tiny image of filial devotion located just to the left of the bureaucrat’s skull. Two small figures stand in the distance, representing the “Paradise Lost” when Dalí and his father were close during his childhood, an image also found in The First Days of Spring.',
//           'In addition to the figures, shadows play a major role in Dalí’s composition. An ominous shadow dominates the barren landscape of the lower right of the painting. Initially resembling the shadow of Mt. Paní from Dalí’s early work, here the shadow has a different reference. Dalí said that this is the shadow cast by a grand piano, meant to create anxiety in the viewer. This piano shadow refers to Dalí’s childhood memories of the Pitxots’ summer concerts, when their piano was moved onto the rocks of Cadaqués. Such specific childhood memories are transformed into ominous presences in Dalí’s work, developing from real memories into nightmarish devices of anxiety.',
//         ],
//         exhibitionHistory: [
//           '1935, Santa Cruz de Tenerife , Ateneo de Santa Cruz de Tenerife, “Exposición Surrealista”',
//           '1938, Amsterdam, Galerie Robert, “Exposition Internationale du Surréalisme”',
//           '1997, Ft. Lauderdale, Ft. Lauderdale Museum of Art, "Treasures from the Salvador Dalí Museum"',
//           '1998, Liverpool, Tate Gallery, “Dali: A Mythology”',
//           '2000, St. Petersburg, Florida, The Salvador Dalí Museum, “James Rosenquist: Paintings James Rosenquist: Selects DALI”',
//           '2002, París, Centre Pompidou, “La Révolution Surréaliste”',
//           '2002, Dusseldorf, Kunstsammiumg Nordrhein-Westfalen, "Surrealismus 1919-1944"',
//           '2006, Tokyo, Ueno Royal Museum, “Dalí Centennial Retrospective”',
//           '2007, London, The Tate Modern, “Dali and Film”',
//           '2008, Los Angeles, Los Angeles County Museum of Art, “Dali and Film”',
//           '2008, New York, Metropolitan Museum of Art, “Dali and Film”',
//         ],
//       },
//       {
//         url: 'http://archive.thedali.org/MWEBimages/Collection Images/2000.21_thumbnail.jpg',
//         title: 'The First Days of Spring',
//         maker: 'Salvador Dalí',
//         dateMade: '1929',
//         placeMade: 'Spain',
//         materials: 'Oil and collage (paper, photograph, postcard, linoleum, transfer decal) on wood panel',
//         dimensions: '19 3/4 in x 25 5/8 in',
//         accessionIDNumber: '2000.21',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           'In his creative autobiography, The Secret Life of Salvador Dalí, the artist describes his process for generating the irrational images found in his early Surrealist paintings: “I spent the whole day seated before my easel, my eyes staring fixedly, trying to ‘see,’ like a medium...the images that would spring up in my imagination.” Few paintings demonstrate the hallucinatory results better than The First Days of Spring. Painted just a few months prior to his joining the Surrealist movement, it presents many of the Freudian symbols and irrational details that characterize his Surrealist period. It is also one of his first uses of collage, skillfully manipulating photos into his composition so that they are indistinguishable from the painted imagery. Dalí proudly referred to this work as a “veritable erotic delirium,” indicating that his goal was to create an abundance of shocking images, painted with astonishingly precise detail.',
//           'Sigmund Freud’s The Interpretation of Dreams is the primary influence behind the painting. Freud proposed that the source of people’s fears, desires and neuroses can be found in their childhood experiences; Dalí places a photo of himself as a child in the center of this canvas, suggesting that various images in the painting might relate to his own childhood memories. A grey wasteland is the stage for his visions, where he places clusters of figures together as if connected through the free associations of dreams.',
//           'A survey of the canvas reveals extraordinary and disturbing details: a postcard of people on a ship enjoying a holiday, representing the audience Dalí wanted to shock; a taboo sexualized couple painted on top of the postcard; an image of a face with a grasshopper attached, recalling Dalí’s childhood fears; a dressed man mounting another dressed man; a father and son looking on from the far distance; an object in the foreground combining a colorful jug and fish with hair and numbers; and on the right, a figure of a young girl with an old man who resembles Freud. The First Days of Spring laid the groundwork for Dalí’s Surrealist career, with many of these images returning over the subsequent years. ',
//         ],
//         exhibitionHistory: [
//           '1929, París, Galerie Goemans, “Dalí”',
//           '1930, Paris, Galerie Goemans, “Exposition de collages”',
//           '1952, Basel, Kunsthalle Basel, “Phantastische Kunst des XX.Jahrhunderts”',
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '1994, Madrid, Museo Nacional Centro de Arte Reina Sofía, "Dalí Joven, 1918-1930"',
//           '1994, New York, Metropolitan Museum of Art, "Dali: The Early Years"',
//           '1994, London, Hayward Gallery, "Dali: The Early Years"',
//           '1995, Barcelona, Palau Robert, "Dali: els Anys Joves, 1918-1930"',
//           '1995, St. Petersburg, Salvador Dali Museum, “The Young Dali: Works from 1914-1930”',
//           '1998, Liverpool, Tate Gallery, “Dali: A Mythology”',
//           '1999, St. Petersburg, Salvador Dalí Museum, “Salvador Dalí: A Mythology”',
//           '1999, Fukuoka, Fukuoka Asian Art Museum, "Dali Exhibition 1999"',
//           '1999, Shinjuku(Tokyo), Mitsukoshi Museum of Art, "Dali Exhibition 1999"',
//           '2000, St. Petersburg, Florida, The Salvador Dalí Museum, "Masterpieces of Surrealism"',
//           '2004, Venezia, Palazzo Grassi, "Dali Retrospective"',
//           '2005, Philadelphia, Philadelphia Museum of Art, "Dali Retrospective"',
//           '2007, London, The Tate Modern, “Dali and Film”',
//           '2008, Los Angeles, Los Angeles County Museum of Art, “Dali and Film”',
//           '2008, New York, Metropolitan Museum of Art, “Dali and Film”',
//           '2009, Melbourne, National Gallery of Victoria, "Salvador Dalí : Liquid Desire"',
//           '2012, Paris, Centre Pompidou, “Dali: Retrospective”',
//           '2013, Madrid, Museo Nacional Reina Sofia, “Dalí. Todas las sugestiones poéticas y todas las posibilidades plásticas”',
//           '2014, St. Petersburg, Salvador Dali Museum, "Picasso/Dali Dali/Picasso"',
//         ],
//       },
//       {
//         url: 'http://archive.thedali.org/MWEBimages/Collection Images/2000.13_thumbnail.jpg',
//         title: 'Oeufs sur le Plat sans le Plat',
//         maker: 'Salvador Dalí',
//         dateMade: '1932',
//         placeMade: 'Spain',
//         materials: 'Oil on canvas',
//         dimensions: '23 3/4 in x 16 1/2 in',
//         accessionIDNumber: '2000.13',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           'This painting was initially inspired by what Dalí called an “intra-uterine memory.” Of this experience, Dalí states, “all enchantment for me was in my eyes and the most splendid…vision [while in the womb] was that of a pair of eggs fried in a pan without a pan...” Dalí claims that he could conjure this intrauterine memory whenever he wished by applying pressure with his fingers to his eyes, stimulating his phosphenes to create bright visual images. In this painting Dalí reproduces the colors that remind him of his mother’s womb: “the intra-uterine paradise was the color of hell…red, orange, yellow, and bluish, the color of flames...”',
//           'The egg suspended on a string represents an embryo attached by the umbilical cord in the fiery orange world, while the shape also suggests a limp phallus. The dripping watch hanging on the lichen covered wall, whose shape mimics the embryonic yoke, is a “soft watch” variant which already had become a Dalínian trademark (representing the fluidness and irrelevance of time in the artist’s dreamy Port Lligat).',
//           'A second inspiration for the painting was Dalí’s desire to pay tribute to Gala. He was reluctant to paint her likeness and instead focused on one of her celebrated attributes – her gaze. The muse to many Surrealists during the 1920s, part of Gala’s power was her unblinking gaze, described by husband Paul Éluard as, “so intense it could pierce walls.” In this work, Dalí makes a surreal metaphoric leap by painting the eggs on the plate with a shimmer he likens to his muse’s piercing gaze.',
//           'The painting’s severe architecture reveals Dalí’s preoccupation with the contrast between geometric architecture and fluid life forms. It may also foreshadow Dalí’s later preoccupation with the architect of Spain’s San Lorenzo de El Escorial Juan de Herrera (1530-1597) and with Ramon Llull (1232-1315), a Catalan mystic obsessed with numerology and inventing a unified system of knowledge. Juan de Herrera was also the author of Discourse on Cubic Form.',
//         ],
//         exhibitionHistory: [
//           '1933, Paris, Pierre Colle, “Exposition Salvador Dali”',
//           '1934, London, Zwemmer Gallery, “Exhibition of Paintings, Drawings and Etchings”',
//           '1956, Knokke Le Zoute, Casino de Knokke Le Zoute, “Salvador Dalí”',
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '1999, Fukuoka, Fukuoka Asian Art Museum, "Dali Exhibition 1999"',
//           '1999, Shinjuku(Tokyo), Mitsukoshi Museum of Art, "Dali Exhibition 1999"',
//           '2001, London, The Tate Modern, “Surrrealism: Desire Unbound"',
//           '2002, New York, The Metropolitan Museum of Art, “Surrrealism: Desire Unbound"',
//           '2006, Tokyo, Ueno Royal Museum, “Dalí Centennial Retrospective”',
//           '2007, St. Petersburg, Fl., Salvador Dalí Museum, “Dalí and the Spanish Baroque”',
//           '2012, Paris, Centre Pompidou, “Dali: Retrospective”',
//           '2013, Madrid, Museo Nacional Reina Sofia, “Dalí. Todas las sugestiones poéticas y todas las posibilidades plásticas”',
//           '2015, Houston, The Menil Collection, “The Secret of the Hanging Egg: Salvador Dali at the Menil”',
//           '2016, St. Petersburg, Fl., Salvador Dalí Museum, "Ferran Adrià: The Invention of Food"',
//         ],
//       },
//       {
//         url:
//           'http://archive.thedali.org/MWEBimages/Collection Images/OILS_images saved for Web/2000.5_Arch-Rem_web.jpg',
//         title: "Archeological Reminiscence of Millet's Angelus",
//         maker: 'Salvador Dalí',
//         dateMade: '1933-35',
//         placeMade: 'Spain',
//         materials: 'Oil on panel',
//         dimensions: '12 1/2 in x 15 1/2 in',
//         accessionIDNumber: '2000.5',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           'The artist visualized the Angelus couple from the painting by Jean-François Millet. As a result of his memories, Dalí paints the figures as ancient towers on the moonlit Ampurdan plain, an atmosphere charged with an eerie, prehistoric quality. In his essay on Millet’s work, Dalí uses a postcard to illustrate how the bowing figures reminded him of the monoliths (menhirs) he saw in parts of Catalonia.',
//           'Dalí paints the female slightly taller than the male, with her features resembling a praying mantis. In his analysis of the painting’s latent meaning, Dalí felt that the female was not only the dominant partner, but also posed a sexual threat to the male, associating her with a female praying mantis. This alludes to Dalí’s assertion that Millet’s painting represents sexual repression, male fear and impotence, and in his work Dalí has updated the popular 19th century Symbolist tradition of the femme fatale into a Surrealist context, extending the message of the implicit dangers of female sensuality.',
//         ],
//         exhibitionHistory: [
//           '1934, Paris, Jacques Bonjean, “Exposition Dali”',
//           '1934, New York, Julien Levy Gallery, “Dali”',
//           '1946, Boston, The Institute of Modern Art, Four Spaniards : Dali, Gris, Miro, Picasso',
//           '1947, Cleveland, Cleveland Museum of Art, “Print Club of Cleveland-Salvador Dalí: An Exhibition”',
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '1996, Barcelona, La Pedrera, “Dalí. Arquitectura”',
//           '1996, Barcelona, Fundacio Caixa de Catalunya, “Dalí. Arquitectura”',
//           '1998, Liverpool, Tate Gallery, “Dali: A Mythology”',
//           '1999, Fukuoka, Fukuoka Asian Art Museum, "Dali Exhibition 1999"',
//           '1999, Shinjuku(Tokyo), Mitsukoshi Museum of Art, "Dali Exhibition 1999"',
//           '2004, Madrid, Museo Nacional Centro de Arte Reina Sofia, “Dalí. Cultura de masses”',
//           '2004, Barcelona, CaixaForum, “Dalí. Cultura de masses”',
//           '2005, Rotterdam, Museum Boijmans van Beuningen, “Salvador Dalí and Mass Culture”',
//           '2005, St. Petersburg, Salvador Dalí Museum, “Salvador Dalí and Mass Culture”',
//           '2006, Tokyo, Ueno Royal Museum, “Dalí Centennial Retrospective”',
//           '2009, Melbourne, National Gallery of Victoria, "Salvador Dalí : Liquid Desire"',
//           '2015, San Francisco, Walt Disney Family Museum, "Disney and Dali: Architects of the Imagination"',
//           '2016, St. Petersburg, Salvador Dali Museum, "Disney and Dali: Architects of the Imagination"',
//         ],
//       },
//       {
//         url:
//           'http://archive.thedali.org/MWEBimages/Collection Images/OILS_images saved for Web/2007.29_Weaning_web.jpg',
//         title: 'Enchanted Beach with Three Fluid Graces',
//         maker: 'Salvador Dalí',
//         dateMade: '1938',
//         placeMade: 'Spain',
//         materials: 'Oil on canvas',
//         dimensions: '25 5/8 in x 32 in',
//         accessionIDNumber: '2000.7',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           "Enchanted Beach offers an example of Dalí's imaginative interpretation of the classical theme of the Three Graces. In art, the symbols of ideal beauty and the handmaidens of Venus. The figure on the right is developed from a detail from an equestrian study by Leonardo da Vinci; Dalí creates a face formed by a distant landscape that is visible through a hole in the rock. The visage of the middle female's face is formed by the horse and figures. The bowed head of the third figure on the left is formed by one of the black rocks in the landscape. The features of a skull can also be found in this area, with the two boulders forming black eye sockets and the gripping fingers forming the skull’s teeth. This painting illustrates the increasing influence of Renaissance and Baroque painters on Dalí. The interplay of perspective and the balance of the elements show an evolving control over his paranoiac-critical illusions.",
//         ],
//         exhibitionHistory: [
//           "1939, New York, Julien Levy Gallery,“Salvador Dalí,” In conjunction with Dali's Dream of Venus Pavillion at the 1939 New York World's Fair",
//           '1941, New York, The Museum of Modern Art, “Salvador Dalí”',
//           '1941, Chicago, The Arts Club of Chicago, “Salvador Dali”',
//           '1941, New York, Julien Levy Gallery, “Salvador Dalí”',
//           '1941, Los Angeles, Dalzell Hatfield Galleries, “Salvador Dalí”',
//           '1942, Indianapolis, The John Herron Art Institute (Indianapolis Museum of Art), [Exhibition of paintings by Salvador Dali]',
//           '1942, San Francisco, California Palace of the Legion of Honor, “An Exhibition of Paintings and Drawings by Dalí”',
//           '1943, Williamsburg, College of William and Mary, “An Exhibition of Paintings and Drawings by Dalí”',
//           '1943, Utica, Munson-Williams-Proctor Arts Institute, “An Exhibition of Paintings and Drawings by Dalí”',
//           '1943, Detroit, Detroit Institute of Arts, “An Exhibition of Paintings and Drawings by Dalí”',
//           '1943, Omaha, Josly Art Museum, “An Exhibition of Paintings and Drawings by Dalí”',
//           '1947, Cleveland, Cleveland Museum of Art, “Print Club of Cleveland-Salvador Dalí: An Exhibition”',
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '1997, Ft. Lauderdale, Ft. Lauderdale Museum of Art, "Treasures from the Salvador Dalí Museum"',
//           '1999, Fukuoka, Fukuoka Asian Art Museum, "Dali Exhibition 1999"',
//           '1999, Shinjuku(Tokyo), Mitsukoshi Museum of Art, "Dali Exhibition 1999"',
//           '1999, Figueres, Dalí Theatre-Museum, “Dream of Venus”',
//           '2002, Miami, Museum of Contemporary Art, “Dream of Venus”',
//           '2003, Düsseldorf, Museum Kunst Palast, “The Endless Enigma : Dalí and the Magicians of Multiple Meaning”',
//           '2006, Tokyo, Ueno Royal Museum, “Dalí Centennial Retrospective”',
//           '2007, St. Petersburg, Fl., Salvador Dalí Museum, “Dalí and the Spanish Baroque”',
//           '2015, St. Petersburg, Salvador Dali Museum, “Dali & da Vinci: Minds, Machines & Masterpieces”',
//         ],
//       },
//       {
//         url:
//           'http://archive.thedali.org/MWEBimages/Collection Images/OILS_images saved for Web/2000.7_Enchanted-Beach_web.jpg',
//         title: 'The Weaning of Furniture-Nutrition',
//         maker: 'Salvador Dalí',
//         dateMade: '1934',
//         placeMade: 'Spain',
//         materials: 'Oil on panel',
//         dimensions: '7 in x 9 1/2 in',
//         accessionIDNumber: '2007.29',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           "The provocatively titled The Weaning of Furniture-Nutrition is a surreal meditation on the word “weaning.” The woman is Dalí's childhood nurse, Llucia, who “weaned” the young Dalí from his mother. Dalí has metaphorically “weaned” Llucia out of her familiar environment, for she is no longer a nurse in his childhood Figueres. Instead, Dalí has posed her as a “net mender” in Port Lligat. In this fishing village, the women mend the torn fishing nets.",
//           'Dalí takes the “weaning” metaphor one step further. As a child, Dalí associated his night table and bottle with his nurse and saw them as an intrinsic part of her being. So in this work he “weaned” them physically out of her body, suggesting that his nurse and these inanimate objects were two parts of the same identity, the furniture fitting in a rectangular hole carved in her back. Their removal creates a void that requires a crutch, Dalí’s symbol of death and impotence. In this painting, the crutch takes on a new meaning and becomes a symbol of solemnity rather than a prop of any kind.',
//         ],
//         exhibitionHistory: [
//           "1934, Barcelona, Galeries d'Art Catalònia, “Salvador Dalí”",
//           '1934, New York, Julien Levy Gallery, “Dali”',
//           '1936, London, Alex, Reid & Lefevre, Ltd., “Salvador Dali”',
//           '1939, San Francisco, San Francisco Golden Gate International Exposition, “Contemporary Art of 79 Countries”',
//           '1941, New York, The Museum of Modern Art, “Salvador Dalí”',
//           "1954, Roma, Sale dell'Aurora Pallavicini, “Mostra di quadri disegni ed oreficerie di Salvador Dalí”",
//           '1954, Venice, “Mostra di quadri disegni ed oreficerie di Salvador Dalí”',
//           '1954, Milan, “Mostra di quadri disegni ed oreficerie di Salvador Dalí”',
//           '1958, New York, The Sidney Janis Gallery, “10th Anniversary Exhibition”',
//           '1958, New York, Carstairs Gallery, “Salvador Dali”',
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '1973, New York, Sidney Janis Gallery, “25 Years of Janis”',
//           '1983, Madrid, Museo Español de Arte Contemporáneo, “400 obras de Salvador Dalí del 1914 al 1983”',
//           '2004, Venezia, Palazzo Grassi, "Dali Retrospective"',
//           '2005, Philadelphia, Philadelphia Museum of Art, "Dali Retrospective"',
//           '2005, Albuquerque, The Albuquerque Museum, “Picasso to Plensa : a century of art from Spain = De Picasso a Plensa : un siglo de arte de España”',
//           '2006, Tokyo, Ueno Royal Museum, “Dalí Centennial Retrospective”',
//         ],
//       },
//       {
//         url: 'http://archive.thedali.org/MWEBimages/Collection Images/2000.19_thumbnail.jpg',
//         title: 'The Discovery of America by Christopher Columbus',
//         otherTitle: 'The Dream of Christoper Columbus',
//         maker: 'Salvador Dalí',
//         dateMade: '1958-59',
//         placeMade: 'Spain',
//         materials: 'Oil on canvas',
//         dimensions: '163 in x 123 1/2 in',
//         accessionIDNumber: '2000.19',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           "This work is an ambitious homage to Dalí's Spain. It combines Spanish history, religion, art and myth into a unified whole. It was commissioned for Huntington Hartford's Gallery of Modern Art on Columbus Circle in New York. At this time, some Catalan historians were claiming that Columbus was actually from Catalonia, not Italy, making the discovery all the more relevant for Dalí, who was also from this region of Spain. Dalí's inspiration for this work was The Surrender of Breda, another painting by Velazquez. Dalí borrows the spears from that painting and places them on the right hand side of his work. Within these spears, Dalí has painted the image of a crucified Christ, which was based on a drawing by the Spanish mystic Saint John. The banner that Columbus is holding bears the likeness of Dalí's wife, Gala. She appears as a saint, suggesting that she is Dalí's muse, and that she is responsible for his own \"discovery of America,\" where he captured the attention of the world through her encouragement. The flies and the bishop at the bottom left are a reference to a Catalan folk legend (from Girona) about Saint Narciso's crypt. Dali uses this myth to underline his patriotic devotion to his homeland's independence.",
//         ],
//         exhibitionHistory: [
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '2005, St. Petersburg, FL Salvador Dali Museum, "Pollock to Pop: America\'s Brush with Dali"',
//           '2007, St. Petersburg, Fl., Salvador Dalí Museum, “Dalí and the Spanish Baroque”',
//         ],
//       },
//       {
//         url:
//           'http://archive.thedali.org/MWEBimages/Collection Images/OILS_images saved for Web/2000.22_Toreador_web.jpg',
//         title: 'The Hallucinogenic Toreador',
//         maker: 'Salvador Dalí',
//         dateMade: '1970',
//         placeMade: 'Spain',
//         materials: 'Oil on canvas',
//         dimensions: '157 in x 117 in',
//         accessionIDNumber: '2000.22',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           'Dalí conceived this painting while in an art supply store in 1968. In the body of Venus, on a box of Venus pencils, he saw the face of the toreador. This double image painting repeats the image of the "Venus de Milo" several times in such a way that the shadows form the features. Start with the green skirt, and make it into a man\'s necktie. The white skirt becomes his shirt. Travel up the figure. Her abdomen becomes his chin, her waist is his mouth, and her left breast is the nose. The pink arch forms the top of the head with the arena at the top as his hat. The tear in the eye (at the nape of Venus\' neck) is shed for the bull. The red skirt on the right Venus is his red cape. ',
//           'The toreador appears again in the figure outlined in yellow with arms raised in dedication of the bull to Gala. She appears in the upper left hand corner surrounded by yellow. Dalí painted Gala with a frown because she disliked bullfights.',
//           'The image of the dying bull emerges from the rocky terrain of Cape Creus that appears just below the cape. A large fly makes up the eye. What might at first appear to be a pool of blood (beneath the dying bull) is really a translucent bay. On this bay a woman floats on a yellow raft. This seeming incongruity symbolizes the "modern tourist invasions of Cape Creus which even the flies of St. Narciso have been unable to halt!" Dalí once remarked that he was not too worried about the profanation of his beloved Cape Creus because its rocks would "eventually vanquish the French tourist, and time would destroy the litter they leave everywhere."',
//         ],
//         exhibitionHistory: [
//           '1970, New York, Knoedler Gallery',
//           '2005, St. Petersburg, Salvador Dali Museum, "Pollock to Pop: America\'s Brush with Dali"',
//           '2007, London, The Tate Modern, “Dali and Film”',
//           '2008, Los Angeles, Los Angeles County Museum of Art, “Dali and Film”',
//           '2008, New York, Metropolitan Museum of Art, “Dali and Film”',
//         ],
//       },
//       {
//         url: 'http://archive.thedali.org/MWEBimages/Collection Images/2000.9_thumbnail.jpg',
//         title: 'Geopoliticus Child Watching the Birth of the New Man',
//         maker: 'Salvador Dalí',
//         dateMade: '1943',
//         placeMade: 'Spain',
//         materials: 'Oil on canvas',
//         dimensions: '18 in x 20 1/2 in',
//         accessionIDNumber: '2000.9',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           'The artist’s notes for the painting read: “1. Parachute, paranaissance (sic), protection, cupola, placenta, Catholicism, Egg, earthly distortion, biological ellipse. Geography changes its skin in historic germination.” Unlike his work from the 1930s, this painting is perhaps easier to decipher because its symbolism is more canonical, downplaying the enigmatic mystery and visual contradictions of his Freudian surrealist period.',
//           'The “new” man pushes his way out of the large egg/globe in the center. He is emerging out of the “new” nation/world power, the United States, Dalí’s temporary home at the time. The enlargement of Africa and South America represents the growing importance of the Third World, and the draped cloth represents the placenta (odd mix of reptile/bird and mammal). An androgynous figure points to the emerging “new man,” showing the cowering “geopoliticus child” the new historical period he will represent. ',
//         ],
//         exhibitionHistory: [
//           '1943, New York, Knoedler Gallery, “An Exhibition of Paintings and Drawings by Dalí”',
//           '1946, Boston, The Institute of Modern Art, “Four Spaniards : Dali, Gris, Miro, Picasso”',
//           '1949, Pittsburgh, Carnegie Institute, “Painting in the United States, 1949”',
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '1999, Fukuoka, Fukuoka Asian Art Museum, "Dali Exhibition 1999"',
//           '1999, Shinjuku(Tokyo), Mitsukoshi Museum of Art, "Dali Exhibition 1999"',
//           '2006, Tokyo, Ueno Royal Museum, “Dalí Centennial Retrospective”',
//           '2007, St. Petersburg, Fl., Salvador Dalí Museum, “Dalí and the Spanish Baroque” ',
//           '2008, Ottawa, National Gallery of Canada, “1930: The Making of a "New Man"',
//           '2012, Paris, Centre Pompidou, “Dali: Retrospective”',
//           '2013, Madrid, Museo Nacional Reina Sofia, “Dalí. Todas las sugestiones poéticas y todas las posibilidades plásticas”',
//         ],
//       },
//       {
//         url:
//           'http://archive.thedali.org/MWEBimages/Collection Images/OILS_images saved for Web/2000.14_Three-Ages_web.jpg',
//         title: 'Old Age, Adolescence, Infancy (The Three Ages)',
//         maker: 'Salvador Dalí',
//         dateMade: '1940',
//         placeMade: 'Spain',
//         materials: 'Oil on canvas',
//         dimensions: '19 5/8 in x 25 5/8 in',
//         accessionIDNumber: '2000.14',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: [
//           'Dalí uses double images derived from his paranoiac-critical method to create the allegorical faces of Old Age, Adolescence, and Infancy. It is through this process Dalí developed these complex, double images used to undermine the irrational world of the image by making it more believable than the viewer’s real world.',
//           "In the Three Ages, glimpses of Port Lligat are seen through the apertures where illusions of faces now appear. These openings were suggested to Dalí by arches of local ruins. On the left, the bowed head of the woman from Millet's Angelus makes up the eye of Old Age; the hole in the brick wall forms her head's outline, and the rest of the figure forms the nose and mouth. The nose and mouth of Adolescence, the figure in the center, is created from the head and scarf of Dalí's nurse sitting on the ground with her back to us. The eyes emerge from the isolated houses seen in the hills across the Bay of Cadaqués. On the right, a fisherwoman repairing a net makes the barely formed face of Infancy. ",
//         ],
//         exhibitionHistory: [
//           '1941, New York, The Museum of Modern Art, “Salvador Dalí”',
//           '1941, Chicago, The Arts Club of Chicago, “Salvador Dali”',
//           '1941, New York, Julien Levy Gallery, “Salvador Dalí”',
//           '1941, Los Angeles, Dalzell Hatfield Galleries, “Salvador Dalí”',
//           '1942, Indianapolis, The John Herron Art Institute (Indianapolis Museum of Art), [Exhibition of paintings by Salvador Dali]',
//           '1942, Indianapolis, The John Herron Art Institute (Indianapolis Museum of Art), [Exhibition of paintings by Salvador Dali]',
//           '1942, San Francisco, California Palace of the Legion of Honor, “An Exhibition of Paintings and Drawings by Dalí”',
//           '1943, Williamsburg, College of William and Mary, “An Exhibition of Paintings and Drawings by Dalí”',
//           '1943, Utica, Munson-Williams-Proctor Arts Institute, “An Exhibition of Paintings and Drawings by Dalí”',
//           '1943, Detroit, Detroit Institute of Arts, “An Exhibition of Paintings and Drawings by Dalí”',
//           '1943, Omaha, Josly Art Museum, “An Exhibition of Paintings and Drawings by Dalí”',
//           '1943, New York, Knoedler Gallery, “An Exhibition of Paintings and Drawings by Dalí”',
//           '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
//           '2000, St. Petersburg, Florida, The Salvador Dalí Museum, “James Rosenquist: Paintings”',
//           '2006, Tokyo, Ueno Royal Museum, “Dalí Centennial Retrospective”',
//           '2009, Paris, Grand Palais, “The Double Image”',
//           '2010, Milan, Palazzo Reale, “Salvador Dalí, il sogno si avvicina(The Dream is Getting Closer)”',
//         ],
//       },
//       {
//         url: 'http://archive.thedali.org',
//         title: '',
//         maker: 'Salvador Dalí',
//         dateMade: '',
//         placeMade: '',
//         materials: '',
//         dimensions: '',
//         accessionIDNumber: '',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: ['', '', ''],
//         exhibitionHistory: ['', '', '', '', '', '', ''],
//       },
//       {
//         url: 'http://archive.thedali.org',
//         title: '',
//         maker: 'Salvador Dalí',
//         dateMade: '',
//         placeMade: '',
//         materials: '',
//         dimensions: '',
//         accessionIDNumber: '',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: ['', '', ''],
//         exhibitionHistory: ['', '', '', '', '', '', ''],
//       },
//       {
//         url: 'http://archive.thedali.org',
//         title: '',
//         maker: 'Salvador Dalí',
//         dateMade: '',
//         placeMade: '',
//         materials: '',
//         dimensions: '',
//         accessionIDNumber: '',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: ['', '', ''],
//         exhibitionHistory: ['', '', '', '', '', '', ''],
//       },
//       {
//         url: 'http://archive.thedali.org',
//         title: '',
//         maker: 'Salvador Dalí',
//         dateMade: '',
//         placeMade: '',
//         materials: '',
//         dimensions: '',
//         accessionIDNumber: '',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: ['', '', ''],
//         exhibitionHistory: ['', '', '', '', '', '', ''],
//       },
//       {
//         url: 'http://archive.thedali.org',
//         title: '',
//         maker: 'Salvador Dalí',
//         dateMade: '',
//         placeMade: '',
//         materials: '',
//         dimensions: '',
//         accessionIDNumber: '',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: ['', '', ''],
//         exhibitionHistory: ['', '', '', '', '', '', ''],
//       },
//       {
//         url: 'http://archive.thedali.org',
//         title: '',
//         maker: 'Salvador Dalí',
//         dateMade: '',
//         placeMade: '',
//         materials: '',
//         dimensions: '',
//         accessionIDNumber: '',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: ['', '', ''],
//         exhibitionHistory: ['', '', '', '', '', '', ''],
//       },
//       {
//         url: 'http://archive.thedali.org',
//         title: '',
//         maker: 'Salvador Dalí',
//         dateMade: '',
//         placeMade: '',
//         materials: '',
//         dimensions: '',
//         accessionIDNumber: '',
//         creditLine: 'Gift of A. Reynolds & Eleanor Morse',
//         onView: true,
//         description: ['', '', ''],
//         exhibitionHistory: ['', '', '', '', '', '', ''],
//       },
//     ],
//     expedition: {},
//     architecture: {},
//     family: {
//       daliDecoded: {},
//       mustache: {},
//     },
//   })
//   .then(() => {
//     console.log('Data Saved!');
//   })
//   .catch(error => {
//     console.log('This failed: ', error);
//   });
