import * as firebase from 'firebase';
import Rebase from 're-base';

// const config = {
//   apiKey: process.env.REACT_APP_FIREBASE_KEY,
//   authDomain: process.env.REACT_APP_FIREBASE_DOMAIN,
//   databaseURL: process.env.REACT_APP_FIREBASE_DATABASE,
//   projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID,
//   storageBucket: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
//   messagingSenderId: process.env.REACT_APP_FIREBASE_SENDER_ID,
// };

const config = {
  apiKey: 'AIzaSyCIHqdl2GqIMEoXn-0oLR5Hm00_eZE1zts',
  authDomain: 'intelli-guide.firebaseapp.com',
  databaseURL: 'https://intelli-guide.firebaseio.com',
  projectId: 'intelli-guide',
  storageBucket: 'intelli-guide.appspot.com',
  messagingSenderId: '846727200470',
};

const app = firebase.initializeApp(config);
const database = firebase.database();

database
  .ref()
  .set({
    copyright:
      'Worldwide rights ©Salvador Dalí. Fundació Gala-Salvador Dalí (Artists Rights Society), 2017 / In the USA ©Salvador Dalí Museum, Inc. St. Petersburg, FL 2017.',
    permanent: [
      {
        title: 'View of Cadaqués with Shadow of Mount Pani',
        url: 'http://archive.thedali.org/MWEBimages/Collection Images/1980.7_thumbnail.jpg',
        maker: 'Salvador Dalí',
        dateMade: 1917,
        placeMade: 'Spain',
        materials: 'Oil on burlap',
        dimensions: '15 1/2 in x 19 in',
        accessionIDNumber: 1980.7,
        creditLine: 'Gift of A. Reynolds & Eleanor Morse',
        onView: true,
        exhibitionHistory: [
          '1925, Barcelona, Galeries Dalmau, "Exposició S. Dalí"',
          '1995, St. Petersburg, Salvador Dali Museum, "The Young Dali: Works from 1914-1930"',
          '2004, Venezia, Palazzo Grassi, "Dalí"',
          '2005, Philadelphia, The Philadelphia Museum of Art, "Dalí"',
          '2016, Tokyo, National Art Center, "Salvador Dalí"',
          '2016, Kyoto, Kyoto Municipal Museum, "Salvador Dalí"',
        ],
        description: [
          'During this period Dalí was experimenting with Impressionism, a 19th Century art movement that sought to capture the immediacy of the visual moment by painting the effects of light on the surfaces of objects. The work is painted on rough burlap, which gives the Bay of Cadaqués scene, with its blocky houses and shimmering sea, an assertive texture. At the invitation of Dalí’s father’s friend Jose Pepito Pichot, Dalí offered to visit the Pichot family estate just outside of Figueres. The Pichots were an extended family whose many members included proficient musicians and artists. Dalí’s father believed an association with this artistic and musically talented family would be very beneficial to his son. In the Pichot dining room, the walls were lined with impressionist paintings, some by Ramon Pichot, an established Impressionist painter and a close friend of Pablo Picasso (1881-1976). One day while looking at Ramon’s works Dalí decided to become a painter. Dalí later said, “Impressionist painting attracted me at the time because it was considered anti-establishment and a revolutionary aesthetic theory.”',
        ],
      },
      {
        title: 'Daddy Longlegs of the Evening-Hope!',
        url: 'http://archive.thedali.org/MWEBimages/Collection Images/2000.6_thumbnail.jpg',
        maker: 'Salvador Dalí',
        dateMade: 1940,
        placeMade: 'Unied States',
        materials: 'Oil on burlap',
        dimensions: '10 in x 20 in',
        accessionIdNumber: 2000.6,
        creditLine: 'Gift of A. Reynolds & Eleanor Morse',
        onView: true,
        history: [
          '1941, Chicago, The Arts Club of Chicago, “Salvador Dali”',
          '1941, New York, Julien Levy Gallery, “Salvador Dalí”',
          '1941, Los Angeles, Dalzell Hatfield Galleries, “Salvador Dalí”',
          '1943, New York, Art of this Century, “Art of this Century : 15 Early Paintings. 15 Late Paintings”',
          '1947, Cleveland, Cleveland Museum of Art, “Print Club of Cleveland-Salvador Dalí: An Exhibition”',
          '1954, Roma, Sale dellAurora Pallavicini, “Mostra di quadri disegni ed oreficerie di Salvador Dalí”',
          '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
          '2000, St. Petersburg, Florida, The Salvador Dalí Museum, “James Rosenquist: Paintings James Rosenquist: Selects DALI”',
          '2004, Venezia, Palazzo Grassi, Dali Retrospective',
          '2005, Philadelphia, Philadelphia Museum of Art, Dali Retrospective',
          '2006, Tokyo, Ueno Royal Museum, “Dalí Centennial Retrospective”',
          '2007, St. Petersburg, Fl., Salvador Dalí Museum, “Dalí and the Spanish Baroque”',
          '2007, St. Petersburg, Fl., Salvador Dalí Museum, “Dalí and the Spanish Baroque”',
          '2009, Melbourne, National Gallery of Victoria, Salvador Dalí : Liquid Desire',
        ],
        description: [
          'Daddy Longlegs of the Evening - Hope! (Araignée du soir, espoir) - 1940. (Including: soft aeroplane, vomited by a cannon, ants, victory born of a broken wing, violoncello in white mastic, and an angel who weeps).',
          'Dalí and his wife, Gala, stayed in the United States from 1940 to 1948 due to the war in Europe which drove him and his fellow Surrealists into exile. This was the first painting Dalí completed after coming to America. The victory referred to in the title is the classical sculpture of the winged Nike of Samothrace who emerges shrouded while rising from the limp airplane. The cannon from the deflated plane is reminiscent of Giorgio de Chirico’s The Philosopher Conquest of 1914. ',
          'An anguished head occupies the center, but here it has become a soft structure infused with sunset colors. The head is metamorphosed into an elastic female figure whose breasts are mimicked by two inkwells (erotic symbols in Dalí’s iconography) which suggest the signing of treaties (and Dalí’s father’s role as a notary). Ants eat away at the figure’s mouth as they do in countless other paintings, indicating the insidious destruction swallowing Europe. The viscous cello and bow suggest that all of Europe’s highest precepts were helpless to prevent the destruction of culture at the hands of a fascist regime.',
          'The painting’s title refers to an old French peasant legend: a spider seen in the evening is a symbol of good luck. ',
        ],
      },
      {
        url: 'http://archive.thedali.org/MWEBimages/Collection Images/1983.1_thumbnail.jpg',
        title: 'Self-Portrait',
        maker: 'Salvador Dalí',
        dateMade: '1921',
        placeMade: 'Spain',
        materials: 'Oil on burlap',
        dimensions: '14 1/2 in x 16 1/2 in',
        accessionIDNumber: '1983.1',
        creditLine: 'Gift of A. Reynolds & Eleanor Morse',
        onView: true,
        description: [
          'This self-portrait was painted during the most tumultuous time in Dalí’s life. Dalí’s mother, Felipa Doménech i Ferrés (1874-1921) died of cancer on February 8, 1921. Yet shortly after, Dalí was accepted to the San Fernando Royal Academy of Fine Arts in Madrid, which he began attending in the fall of 1922. The young artist has represented himself as a young dandy, wearing a large floppy black hat, a black cape, a bold red scarf, and sporting a pipe, creating an unusual appearance that gained him some notoriety among the other students at the Residencia de Estudiantes in Madrid. That Dalí chose to use these props for this early self-portrait indicates that at the age of seventeen, he was already consciously building an eccentric public personality.',
          'Dalí’s eccentricity developed even earlier in an attempt to establish his own distinct identity. Dalí’s identity crisis was the result of having a brother who died nine months before his own birth and who was also named Salvador Dalí. The artist felt that his parents wanted him to be the replacement for the dead brother. Yet Dalí’s eccentricities helped him achieve a separate unique identity.',
          'Notable is the artist’s use of chiaroscuro, a technique where strong dark and light areas are contrasted to produce form.',
          'Notable is the artist’s use of chiaroscuro, a technique where strong dark and light areas are contrasted to produce form.',
        ],
        exhibitionHistory: [
          '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
          '1994, Madrid, Museo Nacional Centro de Arte Reina Sofía, "Dalí Joven, 1918-1930"',
          '1994, New York, Metropolitan Museum of Art, "Dalí: The Early Years"',
          '1994, London, Hayward Gallery, "Dalí: The Early Years"',
          '1995, Barcelona, Palau Robert, "Dalí: els Anys Joves, 1918-1930"',
          '1995, St. Petersburg, Salvador Dali Museum, “The Young Dali: Works from 1914-1930”',
          '1996, San Antonio, San Antonio Museum of Art, “From Gaudi to Tapies: 20th Century Masters”',
          '1996, St. Petersburg, The Salvador Dalí Museum, “From Gaudi to Tapies: 20th Century Masters”',
          '1996, Atlanta, Michael C. Carlos Museum, “From Gaudi to Tapies: 20th Century Masters”',
          '1997, Tacoma, Tacoma Museum of Art',
          '1999, Fukuoka, Fukuoka Asian Art Museum, "Dalí Exhibition 1999"',
          '1999, Shinjuku(Tokyo), Mitsukoshi Museum of Art, "Dalí Exhibition 1999"',
          '2006, Tokyo, Ueno Royal Museum, “Dalí Centennial Retrospective”',
          '2007, Osaka, Suntory Museum, "Dalí Multifaceted : Centenary Exhibition"',
          '2007, Nagoya, Nagoya City Art Museum, "Dalí Multifaceted : Centenary Exhibition"',
          '2007, Sapporo, Hokkaido Museum of Modern Art, "Dalí Multifaceted : Centenary Exhibition"',
          '2007, Figueras, Teatro Museu Dalí, Prestec temporal a la Fundacio Gala-Salvador Dalí per a l\'exposicio "Autoretrats"',
          '2012, Paris, Centre Pompidou, “Dalí Retrospective”',
          '2013, Madrid, Museo Nacional Reina Sofia, “Dalí. Todas las sugestiones poéticas y todas las posibilidades plásticas”',
          '2014, St. Petersburg, Salvador Dalí Museum, "Picasso/Dalí Dalí/Picasso"',
          '2015, Barcelona, Musee Picasso, "Picasso/Dalí Dalí/Picasso"',
        ],
      },
      {
        url: 'http://archive.thedali.org/MWEBimages/Collection Images/1983.2_thumbnail.jpg',
        title: 'Cadaqués',
        maker: 'Salvador Dalí',
        dateMade: '1923',
        placeMade: 'Spain',
        materials: 'Oil on Canvas',
        dimensions: '38 in x 50 in',
        accessionIDNumber: '1983.2',
        creditLine: 'Gift of A. Reynolds & Eleanor Morse',
        onView: true,
        description: [
          'Figueres is located inland from the Costa Brava in an area called the Empordà at the foot of the Pyrenees near the French border. The landscape in this region was to be a major influence and inspiration to Dalí throughout his artistic career. The seemingly endless plain that surrounds Figueres, the distant horizon, the white beaches of Rosas, and the rugged cliffs of the Albares Mountains recur in every period of Dalí’s work. ',
          'In the summers of Dalí’s youth, the family often retreated to their residence in the nearby coastal town. This is an expansive view of Cadaqués from the rock terraces above the Dalí family home. The dynamic composition of this work about his homeland uses a traditional form to establish the subject’s tranquillity. The balloon rising above the landscape and the tiny white sailboat on the expansive bay below create a feeling of lightness and space.',
          'If these seven young women appear similar to one another, it is because Dalí used his sister, Anna Maria (1908–1990), as the model for all of them. She was Dalí’s only sibling and was his primary model in the years before he met his future wife, Gala, in 1929.',
        ],
        exhibitionHistory: [
          '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
          '1994, Madrid, Museo Nacional Centro de Arte Reina Sofía, "Dalí Joven, 1918-1930"',
          '1994, New York, Metropolitan Museum of Art, "Dalí: The Early Years"',
          '1994, London, Hayward Gallery, "Dalí: The Early Years"',
          '1995, Barcelona, Palau Robert, "Dalí: els Anys Joves, 1918-1930"',
          '1995, St. Petersburg, Salvador Dali Museum, “The Young Dali: Works from 1914-1930”',
          '2000, St. Petersburg, Florida, The Salvador Dalí Museum, “James Rosenquist: Paintings James Rosenquist: Selects DALI”',
          '2006, Cleveland, Cleveland Museum of Art, “Barcelona & Modernity: Picasso, Gaudi, Miro, Dalí (1868-1939)”',
          '2007, New York, Metropolitan Museum of Art, “Barcelona & Modernity: Picasso, Gaudi, Miro, Dalí (1868-1939)”',
          '2009, Melbourne, National Gallery of Victoria, "Salvador Dalí : Liquid Desire"',
          '2016, Tokyo, National Art Center, “Salvador Dalí” ',
          '2016, Kyoto, Kyoto Municipal Museum, “Salvador Dalí”',
        ],
      },
      {
        url:
          'http://archive.thedali.org/MWEBimages/Collection Images/OILS_images saved for Web/1983.3_Portrait of My Sister_after conservation_web.jpg',
        title: 'Portrait of My Sister',
        maker: 'Salvador Dalí',
        dateMade: '1923',
        placeMade: 'Spain',
        materials: 'Oil on Canvas',
        dimensions: '1983.3',
        accessionIDNumber: '50 1/4 in x 38 3/4 in x 2 1/2 in',
        creditLine: 'Gift of A. Reynolds & Eleanor Morse',
        onView: true,
        description: [
          'When this work was first exhibited in Spain, it brought the 19-year-old artist considerable fame and was recognized as being comparable to Picasso’s Portrait of Gertrude Stein,1906, or his equally great Women in White, 1923. Dalí completed the first version of Portrait of My Sister in 1923, and originally represented his sister, Anna María, seated in an armchair with her hands crossed in her lap; a small table with books on top occupied the lower right-hand corner. Approximately four years later, Dalí returned to this celebrated canvas and transformed it by adding the second upside-down figure, which radically contrasts with the first and makes the finished painting a double portrait. While there is no documentation that details why Dalí transformed this work so thoroughly, it is believed to be either a reflection of Picasso’s profound influence after their first meeting in 1926, or as a symbol of developing tension between the artist and his sister.',
        ],
        exhibitionHistory: [
          '1965, New York, Gallery of Modern Art, “Salvador Dalí, 1910-1965”',
          '1995, St. Petersburg, Salvador Dali Museum, “The Young Dali: Works from 1914-1930”',
          '2006, Cleveland, Cleveland Museum of Art, “Barcelona & Modernity: Picasso, Gaudi, Miro, Dalí (1868-1939)”',
          '2007, New York, Metropolitan Museum of Art, “Barcelona & Modernity: Picasso, Gaudi, Miro, Dalí (1868-1939)”',
          '2014, St. Petersburg, Salvador Dali Museum, "PicassoDalí Dalí/Picasso"',
          '2015, Barcelona, Musee Picasso, "PicassoDalí Dalí/Picasso"',
        ],
      },
      {
        url: 'http://archive.thedali.org/MWEBimages/Collection Images/1981.1_thumbnail.jpg',
        title: 'The Basket of Bread',
        maker: 'Salvador Dalí',
        dateMade: '1926',
        placeMade: 'Spain',
        materials: 'Oil on Wood panel',
        dimensions: '12 1/2 in x 12 1/2 in',
        accessionIDNumber: '1981.1',
        creditLine: 'Gift of A. Reynolds & Eleanor Morse',
        onView: true,
        description: [
          'This Realist panel demonstrates that by 1926, Dalí’s formative years were drawing to a close; Dalí could achieve mastery in whatever style he chose. This painting has another distinction – it was one of the first Dalí paintings to be seen in America. In 1928 it was exhibited at the Carnegie Institute in Pittsburgh, along with two other works. The artist’s use of detailed illusionism and dramatic lighting against an almost black background alludes to the influence of the Spanish painter Francisco de Zurbarán (1598-1664), demonstrated in his work Still Life with Lemons, Oranges and a Rose, 1633. A contemporary of Diego Velázquez (1599-1660), de Zurbarán was renowned for his works’ austere piety and quiet beauty. Dalí saw bread as the staple of life of the Catalan people. Bread was the most basic element that united Catalans in their daily lives, and like Vermeer and Zurbarán, he renders it as a sublime symbol. ',
          'The painstaking realism of The Basket of Bread was a major achievement and marked a turning point in his career. It boosted Dalí’s ego and gave him a sense of mastery with traditional painting, freeing him to explore more difficult subject matter and imagery. This simple composition of bread in a straw basket on cloth is set dramatically against a dark background. Dalí followed in the Spanish still-life tradition, where a domestic scene represents spiritual reflection. By saturating the objects in such a mysterious light, he transforms the composition into an object of deep contemplation.',
        ],
        exhibitionHistory: [
          '1926, Barcelona, Galeries Dalmau, "Exposició S. Dalí" ',
          '1928, Pittsburgh, Carnegie Institute, "Twenty-Seventh International Exhibition of Paintings"',
          '1932, Pittsburgh, Carnegie Institute, "An Exhibition of Carnegie International Paintings Owned in Pittsburgh"',
          '1941, New York, The Museum of Modern Art, "Salvador Dalí"',
          '1942, Indianapolis, The John Herron Art Institute (Indianapolis Museum of Art), [Exhibition of paintings by Salvador Dali] ',
          '1943, Detroit, Detroit Institute of Arts, "Exhibition of paintings by Salvador Dali"',
          '1946, Boston, The Institute of Modern Art, "Four Spaniards : Dalí, Gris, Miro, Picasso"',
          '1965, New York, Gallery of Modern Art, "Salvador Dalí, 1910-1965"',
          '1993, Figueres, Teatre-Museu Dalí, "Dalí, el Pa"',
          '1994, Madrid, Museo Nacional Centro de Arte Reina Sofía, "Dalí Joven, 1918-1930"',
          '1994, New York, Metropolitan Museum of Art, "Dalí: The Early Years"',
          '1994, London, Hayward Gallery, "Dalí: The Early Years"',
          '1995, Barcelona, Palau Robert, "Dalí: els Anys Joves, 1918-1930"',
          '1995, St. Petersburg, Salvador Dali Museum, “The Young Dali: Works from 1914-1930”',
          '1997, New York, Museum of Modern Art, Objects of Desire: the Modern Still Life"',
          '1998, Pittsburgh, Andy Warhol Museum of Art, “Dalí at the Warhol”',
          '1999, Bilbao, Museo de Bellas Artes de Bilbao, "El Bodegón Español: de Zurbarán a Picasso"',
          '1999, Tokyo, Mitsukoshi Museum of Art, "Dalí Exhibition 1999"',
          '1999, Fukuoka, Fukuoka Asian Art Museum, "Dalí Exhibition 1999"',
          '2004, Venezia, Palazzo Grassi, "Dalí Retrospective"',
          '2005, Philadelphia, Philadelphia Museum of Art, "Dalí Retrospective"',
          '2006, Tokyo, Ueno Royal Museum, "Salvador Dalí Centennial Retrospective"',
          '2007, St. Petersburg, Fl., Salvador Dalí Museum, "Dalí and the Spanish Baroque"',
          '2016, St. Petersburg, Fl., Salvador Dalí Museum, "Ferran Adrià: The Invention of Food"',
          '2017, London, Royal Academy of the Arts, "Dalí/Duchamp"',
          '2018, St. Petersburg, The Dalí Museum, "Dalí/Duchamp"',
        ],
      },
      {
        url:
          'http://archive.thedali.org//MWEBimages/Collection Images/OILS_images saved for Web/1981.2_Girl-with-Curls_web_before conservation.jpg',
        title: 'Girl with Curls',
        maker: 'Salvador Dalí',
        dateMade: '1926',
        placeMade: 'Spain',
        materials: 'Oil on panel',
        dimensions: '20 in x 15 3/4 in',
        accessionIDNumber: '1981.2',
        creditLine: 'Gift of A. Reynolds & Eleanor Morse',
        onView: true,
        description: [
          'This work foreshadows Dalí’s Surrealist style, for it presents a mysterious tableaux painted with hallucinatory clarity. While the blend of realism and distortion in Girl with Curls offers a glimpse of the Surrealist style Dalí would become famous for, it was painted three years before he joined the movement. Several ambiguous elements in the composition make it feel more like a dream than a representation of reality. First, judging by the scale of the building next to the girl, she appears to be too large for the landscape in which she stands. Secondly, the girl’s face is hidden from view, creating a sense of mystery and not providing any psychological details that her features could provide. And lastly, while the landscape is painted in a fairly realistic manner, the curves of the girl’s body are highly exaggerated – looking like she stepped out of a dream. This girl originated in childhood fantasies about a fictional Russian girl whom he nicknamed “Galuchka.” He saw this girl in one of the images in an optical theater/stereoscopic box in the house of his childhood teacher, Señor Trayter. These images “were to stir [Dalí] for the rest of his life”. She became his dream girl onto whom he could project all of his desires.',
          'Dalí pays homage to neoclassicism and its Catalan variant Noucentisme proposed by the writer Eugenio D\'Ors in this alluring painting. Here he represents the unusual the view of a young girl seen from behind and located in an Ampurdán landscape treated in an Italianate style. The representation of a figure viewed from behind is a pretext for painting the expansive landscape imbued with psychological tension, with its high sky and dramatic crescent moon, as we are invited to look over her shoulder and therefore identify with her point of view. Though her sculptural pose ( or "contrapposto") and the treatment of the landscape point to classical motifs, the device of looking over her shoulder derives from Romantic painting, and her exaggeratedly curving hips introduce the erotic into what is otherwise a restrained subject.',
          "Dalí later explained how this figure was transformed from the adolescent girl Dullita into the literary figure of Gradiva and eventually reborn as his wife Gala. Gradiva was a mythic, literary phantasm, who was notable for how her foot was elegantly raised when walking, the subject of a popular novel analyzed by Freud at the beginning of the 1900s, but only translated into French in 1931. At this time Dalí adopted this subject, making it part of his personal mythology and imbuing this figure with subjective symbolism. Indeed, Gradiva became one of the artist's central concerns during the 1930s.",
        ],
        exhibitionHistory: [
          '1926, Barcelona, Galeries Dalmau, "Exposició S. Dalí"',
          '1962, Madrid, Casón del Buen Retiro, "Exposición de pintura catalana : desde la prehistoria hasta nuestros días"',
          '1965, New York, Gallery of Modern Art, "Salvador Dalí, 1910-1965"',
          '1995, St. Petersburg, Salvador Dali Museum, “The Young Dali: Works from 1914-1930”',
          '1998, Liverpool, Tate Gallery Liverpool, "Salvador Dalí: a Mythology"',
          '2000, St. Petersburg, Florida, Salvador Dalí Museum, "James Rosenquist: Paintings"',
          '2002, Madrid, Museo Thyssen-Bornemisza, "Dalí : Gradiva"',
          '2016, Tokyo, National Art Center, “Salvador Dalí” ',
          '2016, Kyoto, Kyoto Municipal Museum, “Salvador Dalí”',
        ],
      },
    ],
    expedition: {},
    architecture: {},
    family: {
      daliDecoded: {},
      mustache: {},
    },
  })
  .then(() => {
    console.log('Data Saved!');
  })
  .catch(error => {
    console.log('This failed: ', error);
  });
